name: Deploy Next.js App
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/abu-project:latest .
      - name: Verify Docker image
        run: docker images
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/abu-project:latest
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > id_rsa
          chmod 600 id_rsa
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
            docker stop ${{ secrets.DOCKER_HUB_USERNAME }}/abu-project:latest || true
            docker rm ${{ secrets.DOCKER_HUB_USERNAME }}/abu-project:latest || true
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/abu-project:latest
            docker run -d ${{ secrets.DOCKER_HUB_USERNAME }}/abu-project:latest -p 3003:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/abu-project:latest
          EOF
